[Logger]
LogLevel = "debug"

[DatabaseConfig]
DatabaseURL = "host=localhost dbname=steamrest_dev sslmode=disable"

[ServerConfig]
BindAddr = "localhost:8080"
InfoRoute = "/info/{id:[0-9]+}"

[ControllerConfig]
Format = "json"
AppList = "https://api.steampowered.com/ISteamApps/GetAppList/v2/"
AppDetails = "http://store.steampowered.com/api/appdetails/"